### ISSUE TITLE
[chore] Fix broken assets

### ISSUE THREAD

**Issue by jfmcquade** [IDEMSInternational/app-debug-content#97]
Ever since the debug deployment was broken out into this dedicated content repo, there have been many references to assets within templates that do not exist in the deployment's [assets folder](https://drive.google.com/drive/u/1/folders/1bnGPB70wPp9hzVOpT4LkPX9h3FwIrqfs).

Now that we have the reports feature (https://github.com/IDEMSInternational/open-app-builder/pull/2429), we can easily access a list of broken asset links, see summary here: https://github.com/IDEMSInternational/app-debug-content/blob/main/reports/summary.md. This should be used to work through the debug templates and fix any asset links, either linking to existing debug assets or potentially adding new ones where necessary.

**Comment by esmeetewinkel** [comment]
Worked on this in PRs #98 #99 #100 #101
